parameters:
    database_driver: pdo_pgsql
    database_host: wallabagdb
    database_port: 5432
    database_name: wallabag
    database_user: wallabag
    database_password: password
    test_database_driver: pdo_pgsql
    test_database_host: wallabagdb
    test_database_port: 5432
    test_database_name: wallabag
    test_database_user: wallabag
    test_database_password: password
    mailer_transport: smtp
    mailer_host: smtp
    twofactor_sender: wallabag@mais-h.eu
    warning_message:
    download_pictures: true
    wallabag_url: http://save.mais-h.eu
    from_email: wallabag@mais-h.eu
