parameters:
    database_driver: pdo_pgsql
    database_host: localhost
    database_port: 5432
    database_name: wallabag
    database_user: wallabag
    database_password: password
    test_database_driver: pdo_pgsql
    test_database_host: localhost
    test_database_port: 5432
    test_database_name: wallabag
    test_database_user: wallabag
    test_database_password: password
    from_email: wallabag@mais-h.eu
    wallabag_url: http://save.mais-h.eu
    warning_message:
    twofactor_sender: wallabag@mais-h.eu
