apiVersion: v1
kind: Pod
metadata:
  name: wallabag-initdb
  labels:
    app: wallabag-initdb
spec:
  containers:
  - name: wallabag
    image: mathbruyen/wallabag:20160224
    command:
    - bash
    - -c
    - "composer run-script build-parameters -- --no-interaction && php bin/console doctrine:schema:update --force"
    env:
    - name: SYMFONY__WALLABAG_DB_HOST
      value: !wallabag db service ip!
    - name: SYMFONY__WALLABAG_DB_NAME
      value: wallabag
    - name: SYMFONY__WALLABAG_DB_USER
      value: wallabag
    - name: SYMFONY__WALLABAG_DB_PASSWORD
      value: password
    resources:
      requests:
        cpu: 100m
        memory: 100Mi
