apiVersion: v1
kind: ReplicationController
metadata:
  name: wallabag-v4
  labels:
    app: wallabag
    version: v4
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: wallabag
        version: v4
    spec:
      containers:
      - name: wallabag
        image: mathbruyen/wallabag:20151210-2
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
        ports:
        - containerPort: 80
        env:
        - name: WALLABAG_SECRET
          value: supersecret
        volumeMounts:
          - name: assets-disk
            mountPath: /wallabag/data/assets
        ports:
        - containerPort: 5432
      volumes:
      - name: assets-disk
        gcePersistentDisk:
          pdName: wallabagassets-disk
          fsType: ext4
