apiVersion: v1
kind: ReplicationController
metadata:
  name: wallabag-v6
  labels:
    app: wallabag
    version: v6
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: wallabag
        version: v6
    spec:
      containers:
      - name: wallabag
        image: mathbruyen/wallabag:20160128-2
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
        ports:
        - containerPort: 80
        env:
        - name: WALLABAG_SECRET
          value: supersecret
        ports:
        - containerPort: 5432
