apiVersion: v1
kind: ReplicationController
metadata:
  name: wallabag-v11
  labels:
    app: wallabag
    version: v11
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: wallabag
        version: v11
    spec:
      containers:
      - name: wallabag
        image: mathbruyen/wallabag:20160924
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
        ports:
        - containerPort: 80
        env:
        - name: SYMFONY__WALLABAG_DB_HOST
          value: wallabagdb
        - name: SYMFONY__WALLABAG_DB_NAME
          value: wallabag
        - name: SYMFONY__WALLABAG_DB_USER
          value: wallabag
        - name: SYMFONY__WALLABAG_DB_PASSWORD
          value: password
        - name: SYMFONY__WALLABAG_SMTP_HOST
          value: smtp
        - name: SYMFONY__WALLABAG_SECRET
          value: !session secret! 
        livenessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 60
          timeoutSeconds: 5
