apiVersion: v1
kind: ReplicationController
metadata:
  name: wallabagdb
  labels:
    app: wallabagdb
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: wallabagdb
    spec:
      containers:
      - name: wallabagdb
        image: postgres
        env:
        - name: POSTGRES_PASSWORD
          value: password
        - name: POSTGRES_USER
          value: wallabag
        - name: PGDATA
          value: /var/lib/postgresql/data/pgdata
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
        volumeMounts:
          - name: db-disk
            mountPath: /var/lib/postgresql/data
        ports:
        - containerPort: 5432
      volumes:
      - name: db-disk
        gcePersistentDisk:
          pdName: wallabagdb-disk
          fsType: ext4
