apiVersion: v1
kind: ReplicationController
metadata:
  name: wallabag-v2
  labels:
    app: wallabag
    version: v2
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: wallabag
        version: v2
    spec:
      containers:
      - name: wallabag
        image: mathbruyen/wallabag:20151203
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
        ports:
        - containerPort: 80
        env:
        - name: WALLABAG_MAILER_HOST
          value: smtp
        - name: WALLABAG_MAILER_PORT
          value: "25"
        - name: WALLABAG_MAILER_USER
          value:
        - name: WALLABAG_MAILER_PASSWORD
          value:
        - name: WALLABAG_SECRET
          value: supersecret
