apiVersion: v1
kind: ReplicationController
metadata:
  name: wallabag-v7
  labels:
    app: wallabag
    version: v7
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: wallabag
        version: v7
    spec:
      containers:
      - name: wallabag
        image: mathbruyen/wallabag:20160128-2
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
        ports:
        - containerPort: 80
        env:
        - name: WALLABAG_SECRET
          value: supersecret
        livenessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 60
          timeoutSeconds: 5
