apiVersion: v1
kind: ReplicationController
metadata:
  name: wallabag-v8
  labels:
    app: wallabag
    version: v8
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: wallabag
        version: v8
    spec:
      containers:
      - name: wallabag
        image: mathbruyen/wallabag:20160224
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
        ports:
        - containerPort: 80
        env:
        - name: SYMFONY__WALLABAG_DB_HOST
          value: !wallabag db service ip!
        - name: SYMFONY__WALLABAG_DB_NAME
          value: wallabag
        - name: SYMFONY__WALLABAG_DB_USER
          value: wallabag
        - name: SYMFONY__WALLABAG_DB_PASSWORD
          value: password
        livenessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 60
          timeoutSeconds: 5
