apiVersion: v1
kind: ReplicationController
metadata:
  name: dckeldb
  labels:
    app: dckeldb
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: dckeldb
    spec:
      containers:
      - name: dckeldb
        image: postgres
        env:
        - name: POSTGRES_PASSWORD
          value: password
        - name: POSTGRES_USER
          value: dckel
        - name: PGDATA
          value: /var/lib/postgresql/data/pgdata
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
        volumeMounts:
          - name: db-disk
            mountPath: /var/lib/postgresql/data
        ports:
        - containerPort: 5432
      volumes:
      - name: db-disk
        gcePersistentDisk:
          pdName: dckeldb-disk
          fsType: ext4
