apiVersion: v1
kind: ReplicationController
metadata:
  name: dckel-v4
  labels:
    app: dckel
    version: v4
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: dckel
        version: v4
    spec:
      containers:
      - name: dckel
        image: mathbruyen/dckel:20160111
        env:
        - name: DB
          value: postgres://dckel:password@dckeldb:5432/dckel
        - name: SECRET
          value: !secret!
        - name: PORT
          value: "80"
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
        ports:
        - containerPort: 80
