apiVersion: v1
kind: Pod
metadata:
  name: dckel-initdb
  labels:
    app: dckel-initdb
spec:
  containers:
  - name: dckel
    image: mathbruyen/dckel:20160212
    command:
    - npm
    - run
    - sync-db
    env:
    - name: DB
      value: postgres://dckel:password@dckeldb:5432/dckel
    resources:
      requests:
        cpu: 100m
        memory: 100Mi
