apiVersion: v1
kind: ReplicationController
metadata:
  name: ssh
  labels:
    app: sshd
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: sshd
    spec:
      containers:
      - name: sshd
        image: mathbruyen/sshd:0.0.2
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
        ports:
        - containerPort: 22
