apiVersion: v1
kind: ReplicationController
metadata:
  name: tinytinyrss
  labels:
    app: tinytinyrss
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: tinytinyrss
    spec:
      containers:
      - name: tinytinyrss
        image: clue/ttrss
        env:
        - name: DB_ENV_PASS
          value: password
        - name: DB_ENV_USER
          value: tinytiny
        - name: DB_HOST
          value: localhost
        - name: DB_PORT
          value: "5432"
        - name: SELF_URL_PATH
          value: https://feeds.mais-h.eu
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
        ports:
        - containerPort: 80
      - name: tinytinyrssdb
        image: postgres
        env:
        - name: POSTGRES_PASSWORD
          value: password
        - name: POSTGRES_USER
          value: tinytiny
        - name: PGDATA
          value: /var/lib/postgresql/data/pgdata
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
        volumeMounts:
          - name: db-disk
            mountPath: /var/lib/postgresql/data
      volumes:
      - name: db-disk
        gcePersistentDisk:
          pdName: tinytinyrssdb-disk
          fsType: ext4
