apiVersion: v1
kind: ReplicationController
metadata:
  name: wallabag-v1
  labels:
    app: wallabag
    version: v1
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: wallabag
        version: v1
    spec:
      containers:
      - name: wallabag
        image: mathbruyen/wallabag:20151124
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
        command:
        - php
        - app/console
        - server:run
        - 0.0.0.0:80
        ports:
        - containerPort: 80
      - name: wallabagdb
        image: postgres
        env:
        - name: POSTGRES_PASSWORD
          value: password
        - name: POSTGRES_USER
          value: wallabag
        - name: PGDATA
          value: /var/lib/postgresql/data/pgdata
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
        volumeMounts:
          - name: db-disk
            mountPath: /var/lib/postgresql/data
      volumes:
      - name: db-disk
        gcePersistentDisk:
          pdName: wallabagdb-disk
          fsType: ext4
