apiVersion: v1
kind: ReplicationController
metadata:
  name: web-v2
  labels:
    app: web
    version: v2
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: web
        version: v2
    spec:
      containers:
      - name: nginx
        image: mathbruyen/web:0.0.3
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
        ports:
        - containerPort: 80
