apiVersion: v1
kind: ReplicationController
metadata:
  name: blog-v10
  labels:
    app: blog
    version: v10
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: blog
        version: v10
    spec:
      containers:
      - name: nginx
        image: mathbruyen/blog:20170211
        resources:
          requests:
            cpu: 10m
            memory: 10Mi
        ports:
        - containerPort: 80
        livenessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 60
          timeoutSeconds: 5
