apiVersion: v1
kind: ReplicationController
metadata:
  name: blog-v1
  labels:
    app: blog
    version: v1
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: blog
        version: v1
    spec:
      containers:
      - name: jekyll
        image: jekyll/jekyll:pages
        resources:
          requests:
            cpu: 50m
            memory: 100Mi
        command:
        - sh
        - -c
        - "git clone --depth 1 -b gh-pages https://github.com/mathbruyen/blog.git /srv/jekyll && jekyll serve"
        ports:
        - containerPort: 4000
        livenessProbe:
          httpGet:
            path: /
            port: 4000
          initialDelaySeconds: 60
          timeoutSeconds: 5
