apiVersion: v1
kind: ReplicationController
metadata:
  name: tinytinyrssdb
  labels:
    app: tinytinyrssdb
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: tinytinyrssdb
    spec:
      containers:
      - name: tinytinyrssdb
        image: postgres:9.5.3
        env:
        - name: POSTGRES_PASSWORD
          value: password
        - name: POSTGRES_USER
          value: tinytiny
        - name: PGDATA
          value: /var/lib/postgresql/data/9.5
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
        volumeMounts:
          - name: db-disk
            mountPath: /var/lib/postgresql/data
        ports:
        - containerPort: 5432
        livenessProbe:
          exec:
            command:
            - psql
            - --dbname=ttrss
            - --username=tinytiny
            - --command=\dt
          initialDelaySeconds: 60
          timeoutSeconds: 3
      volumes:
      - name: db-disk
        gcePersistentDisk:
          pdName: tinytinyrssdb-disk
          fsType: ext4
