apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: tiles
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: tiles
    spec:
      containers:
      - name: nginx
        image: nginx:1.12.0-alpine
        resources:
          requests:
            cpu: 10m
            memory: 10Mi
        ports:
        - containerPort: 80
        volumeMounts:
        - name: config
          mountPath: /etc/nginx/conf.d
          readOnly: true
        - name: tiles
          mountPath: /tiles
      volumes:
      - name: tiles
        emptyDir:
      - name: config
        configMap:
          name: tiles-config-v1
