apiVersion: v1
kind: ReplicationController
metadata:
  name: tiles-v2
  labels:
    app: tiles
    version: v2
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: tiles
        version: v2
    spec:
      containers:
      - name: nginx
        image: nginx:1.11.4-alpine
        resources:
          requests:
            cpu: 10m
            memory: 10Mi
        ports:
        - containerPort: 80
        volumeMounts:
        - name: config
          mountPath: /etc/nginx/conf.d
          readOnly: true
        - name: tiles
          mountPath: /tiles
      volumes:
      - name: tiles
        emptyDir:
      - name: config
        configMap:
          name: tiles-config-v1
