apiVersion: v1
kind: ReplicationController
metadata:
  name: web-v9
  labels:
    app: web
    version: v9
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: web
        version: v9
    spec:
      containers:
      - name: nginx
        image: mathbruyen/web:0.0.9
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
        ports:
        - containerPort: 80
        - containerPort: 443
        volumeMounts:
        - name: certificates
          mountPath: /etc/certificates
          readOnly: true
      volumes:
      - name: certificates
        secret:
          secretName: webcertificates-v1
        
