apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: web
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
      - name: nginx
        image: nginx:1.12.0-alpine
        resources:
          requests:
            cpu: 10m
            memory: 10Mi
        ports:
        - containerPort: 80
        - containerPort: 443
        volumeMounts:
        - name: config
          mountPath: /etc/nginx/conf.d
          readOnly: true
        - name: certificates
          mountPath: /etc/certificates
          readOnly: true
      volumes:
      - name: certificates
        secret:
          secretName: webcertificates-v14
      - name: config
        configMap:
          name: web-config-v9
