apiVersion: v1
kind: ReplicationController
metadata:
  name: web-v19
  labels:
    app: web
    version: v19
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: web
        version: v19
    spec:
      containers:
      - name: nginx
        image: nginx:1.9.10
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
        ports:
        - containerPort: 80
        - containerPort: 443
        volumeMounts:
        - name: config
          mountPath: /etc/nginx/conf.d
          readOnly: true
        - name: certificates
          mountPath: /etc/certificates
          readOnly: true
      volumes:
      - name: certificates
        secret:
          secretName: webcertificates-v6
      - name: config
        secret:
          secretName: webconfiguration-v7
