apiVersion: v1
kind: ReplicationController
metadata:
  name: web-v36
  labels:
    app: web
    version: v36
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: web
        version: v36
    spec:
      containers:
      - name: nginx
        image: nginx:1.11.4
        resources:
          requests:
            cpu: 50m
            memory: 100Mi
        ports:
        - containerPort: 80
        - containerPort: 443
        volumeMounts:
        - name: config
          mountPath: /etc/nginx/conf.d
          readOnly: true
        - name: certificates
          mountPath: /etc/certificates
          readOnly: true
      volumes:
      - name: certificates
        secret:
          secretName: webcertificates-v11
      - name: config
        configMap:
          name: web-config-v6
