apiVersion: v1
kind: ReplicationController
metadata:
  name: web-v41
  labels:
    app: web
    version: v41
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: web
        version: v41
    spec:
      containers:
      - name: nginx
        image: nginx:1.11.8
        resources:
          requests:
            cpu: 10m
            memory: 10Mi
        ports:
        - containerPort: 80
        - containerPort: 443
        volumeMounts:
        - name: config
          mountPath: /etc/nginx/conf.d
          readOnly: true
        - name: certificates
          mountPath: /etc/certificates
          readOnly: true
      volumes:
      - name: certificates
        secret:
          secretName: webcertificates-v13
      - name: config
        configMap:
          name: web-config-v9
