apiVersion: v1
kind: ReplicationController
metadata:
  name: web-v4
  labels:
    app: web
    version: v4
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: web
        version: v4
    spec:
      containers:
      - name: nginx
        image: mathbruyen/web:0.0.5
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
        ports:
        - containerPort: 80
